project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!homework/"
    - "!exams/"
    - "!outcomes/"
    - "!ShinyApps/"
    - "!Tyson-HWs-Journal/"
    - "!Visuals_Plotly_Copy/"
    - "backend_files"

  resources:
    - homework
    - .nojekyll
    - data
    - exams

website:
  title: "BYU-Idaho Time Series"
  favicon: images/TSFavicon.png
  page-navigation: true
  navbar:
      background: primary
      logo: images/TSfavicon_inv.png
      left:
        - text: "Table of Contents"
          file: index.qmd
        - text: "Resources"
          file: resource_blog.qmd
        - sidebar:chapter_1
        - sidebar:chapter_2
        - sidebar:chapter_3
        - sidebar:chapter_4
        - sidebar:chapter_5
        - sidebar:chapter_6
        - sidebar:chapter_7
        - sidebar:newSequence

  sidebar:
    - id: chapter_1
      title: "Chapter 1"
      style: "docked"
      collapse-level: 1
      contents:
        - section: "Overview"
          contents:
            - chapter_1.qmd
        - section: "Lesson 1"
          contents:
            - chapter_1_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_1_lesson_2.qmd
        - section: "Lesson 3"
          contents:
            - chapter_1_lesson_3.qmd
        - section: "Lesson 4"
          contents:
            - chapter_1_lesson_4.qmd
        - section: "Lesson 5"
          contents:
            - chapter_1_lesson_5.qmd

    - id: chapter_2
      title: "Chapter 2"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Overview"
          contents:
            - chapter_2.qmd
        - section: "Lesson 1"
          contents:
            - chapter_2_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_2_lesson_2.qmd
        - section: "Lesson 3"
          contents:
            - chapter_2_lesson_3.qmd

    - id: chapter_3
      title: "Chapter 3"
      style: "docked"
      collapse-level: 2
      contents:
#        - auto: "*_3.qmd" # if we redid the naming scheme like below we could use auto population methods
#        - chapter_3/lesson_1_chapter_3.qmd
        - section: "Overview"
          contents:
            - chapter_3.qmd
        - section: "Lesson 1"
          contents:
            - chapter_3_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_3_lesson_2.qmd
        - section: "Lesson 3"
          contents:
            - chapter_3_lesson_3.qmd
        - section: "Lesson 4"
          contents:
            - chapter_3_lesson_4.qmd
        - section: "Lesson 5"
          contents:
            - chapter_3_lesson_5.qmd

    - id: chapter_4
      title: "Chapter 4"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Overview"
          contents:
            - chapter_4.qmd
        - section: "Lesson 1"
          contents:
            - chapter_4_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_4_lesson_2.qmd
        - section: "Lesson 3"
          contents:
            - chapter_4_lesson_3.qmd
        - section: "Lesson 4"
          contents:
            - chapter_4_lesson_4.qmd

    - id: chapter_5
      title: "Chapter 5"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Overview"
          contents:
            - chapter_5.qmd
        - section: "Lesson 1"
          contents:
            - chapter_5_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_5_lesson_2.qmd
        - section: "Lesson 3"
          contents:
            - chapter_5_lesson_3.qmd
        - section: "Lesson 4"
          contents:
            - chapter_5_lesson_4.qmd
        - section: "Lesson 5"
          contents:
            - chapter_5_lesson_5.qmd

    - id: chapter_6
      title: "Chapter 6"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Overview"
          contents:
            - chapter_6.qmd
        - section: "Lesson 1"
          contents:
            - chapter_6_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_6_lesson_2.qmd


    - id: chapter_7
      title: "Chapter 7"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Overview"
          contents:
            - chapter_7.qmd
        - section: "Lesson 1"
          contents:
            - chapter_7_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_7_lesson_2.qmd
        - section: "Lesson 2"
          contents:
            - chapter_7_lesson_3.qmd


    - id: newSequence
      title: "New Sequence"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Chapter 1"
          contents:
            - NewSequence/Chapter_1_New.qmd
        - section: "Chapter 2"
          contents:
            - NewSequence/Chapter_2_New.qmd
        - section: "Chapter 3"
          contents:
            - NewSequence/Chapter_3_New.qmd
        - section: "Chapter 4"
          contents:
            - NewSequence/Chapter_4_New.qmd
        - section: "Chapter 5"
          contents:
            - NewSequence/Chapter_5_New.qmd
        - section: "Chapter 6"
          contents:
            - NewSequence/Chapter_6_New.qmd
        - section: "Chapter 7"
          contents:
            - NewSequence/Chapter_7_New.qmd


format:
  html:
    theme:
      light: [cosmo, theme-byui.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: source


